# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: 'npm' # See documentation for possible values
      directory: '/frontend/nuxt-app/' # Location of package manifests
      target-branch: 'main'
      schedule:
          interval: 'weekly'
          day: 'friday'
          time: '08:00'
          timezone: 'Europe/Zurich'
      assignees:
          - '21r8390'
      commit-message:
          prefix: '⬆️: '
      labels:
          - 'nuxt'
          - 'dependencies'
      open-pull-requests-limit: 5
