version = 1

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true